import unicodedata

MAPEAMENTO = {
    # TRANSPORTE
    "uber": "transporte",
    "taxi": "transporte",
    "cabify": "transporte",
    "posto": "transporte",
    "gasolina": "transporte",
    "etanol": "transporte",
    "combustivel": "transporte",
    "estacionamento": "transporte",
    "pedagio": "transporte",
    "nutag": "transporte",        # NuTag = tag de pedágio do Nubank
    "shellbox": "transporte",     # Shell Pay
    "shell": "transporte",
    "ipiranga": "transporte",
    "petrobras": "transporte",
    "br distribuidora": "transporte",
    "localiza": "transporte",     # Aluguel de carro
    "movida": "transporte",
    "unidas": "transporte",
    "sem parar": "transporte",
    "veloe": "transporte",
    "autopass": "transporte",
    "onibus": "transporte",
    "metro": "transporte",
    "mototaxi": "transporte",
    "corridas": "transporte",
    "motoca": "transporte",
    "patinete": "transporte",
    "bicicleta": "transporte",
    "mobilidade": "transporte",   # Easyjet Mobilidade, etc.
    "easyjet": "transporte",
    "rappi": "transporte",
    "indriver": "transporte",
    "auto posto": "transporte",

    # ALIMENTAÇÃO
    "ifood": "alimentação",
    "ifd": "alimentação",         # Prefixo IFD* do iFood
    "restaurante": "alimentação",
    "lanchonete": "alimentação",
    "padaria": "alimentação",
    "panificadora": "alimentação",
    "padoca": "alimentação",
    "boulangerie": "alimentação",
    "confeitaria": "alimentação",
    "doceria": "alimentação",
    "cafe": "alimentação",
    "cafeteria": "alimentação",
    "mc donalds": "alimentação",
    "mcdonalds": "alimentação",
    "mcdonald": "alimentação",
    "burger king": "alimentação",
    "pizza": "alimentação",
    "pizzaria": "alimentação",
    "hamburguer": "alimentação",
    "burguer": "alimentação",
    "burger": "alimentação",
    "lanche": "alimentação",
    "lanches": "alimentação",
    "suco": "alimentação",
    "sucos": "alimentação",
    "acai": "alimentação",
    "acaiteria": "alimentação",
    "sorvete": "alimentação",
    "sorveteria": "alimentação",
    "churrascaria": "alimentação",
    "churrasco": "alimentação",
    "rodizio": "alimentação",
    "sushi": "alimentação",
    "japonesa": "alimentação",
    "chinese": "alimentação",
    "tapioca": "alimentação",
    "pastel": "alimentação",
    "emporio": "alimentação",
    "mercearia": "alimentação",
    "delicatessen": "alimentação",
    "kebab": "alimentação",
    "subway": "alimentação",
    "sandwich": "alimentação",
    "grill": "alimentação",
    "kitchen": "alimentação",
    "food": "alimentação",
    "steakhouse": "alimentação",
    "poke": "alimentação",
    "crepe": "alimentação",
    "tacos": "alimentação",
    "temaki": "alimentação",
    "yakisoba": "alimentação",
    "espetinho": "alimentação",
    "bistrô": "alimentação",
    "bistro": "alimentação",
    "bar e": "alimentação",       # "Bar e Restaurante"
    "mp *pupos": "alimentação",
    "alecrim": "alimentação",     # Restaurante recorrente no extrato

    # SUPERMERCADO
    "supermercado": "supermercado",
    "mercado": "supermercado",
    "hipermercado": "supermercado",
    "minimercado": "supermercado",
    "atacadao": "supermercado",
    "atacado": "supermercado",
    "assai": "supermercado",
    "carrefour": "supermercado",
    "pao de acucar": "supermercado",
    "extra": "supermercado",
    "savegnago": "supermercado",  # Rede de SP/interior
    "bistek": "supermercado",
    "sonda": "supermercado",
    "prezunic": "supermercado",
    "coop": "supermercado",
    "st marche": "supermercado",
    "walmart": "supermercado",
    "hortifruti": "supermercado",
    "hortifruit": "supermercado",
    "quitanda": "supermercado",
    "sacolao": "supermercado",
    "hortigranjeiro": "supermercado",
    "feira": "supermercado",
    "frutaria": "supermercado",
    "verdureiro": "supermercado",

    # SAÚDE
    "farmacia": "saúde",
    "drogaria": "saúde",
    "droga raia": "saúde",
    "drogasil": "saúde",
    "ultrafarma": "saúde",
    "pacheco": "saúde",
    "nissei": "saúde",
    "hospital": "saúde",
    "clinica": "saúde",
    "medico": "saúde",
    "consulta": "saúde",
    "exame": "saúde",
    "laboratorio": "saúde",
    "dentista": "saúde",
    "odonto": "saúde",
    "otica": "saúde",
    "oculos": "saúde",
    "academia": "saúde",
    "smartfit": "saúde",
    "bluefit": "saúde",
    "bodytech": "saúde",
    "crossfit": "saúde",
    "pilates": "saúde",
    "yoga": "saúde",
    "fisioterapia": "saúde",
    "fisio": "saúde",
    "psicologo": "saúde",
    "psiquiatra": "saúde",
    "terapia": "saúde",
    "nutricionist": "saúde",
    "unimed": "saúde",
    "amil": "saúde",
    "hapvida": "saúde",
    "notredame": "saúde",
    "plano de saude": "saúde",
    "vacina": "saúde",
    "remedio": "saúde",
    "medicamento": "saúde",
    "suplemento": "saúde",
    "whey": "saúde",
    "vitamina": "saúde",

    # BELEZA
    "barbearia": "beleza",
    "barbeiro": "beleza",
    "barber": "beleza",
    "salao": "beleza",
    "cabeleireiro": "beleza",
    "estetica": "beleza",
    "manicure": "beleza",
    "pedicure": "beleza",
    "sobrancelha": "beleza",
    "depilacao": "beleza",
    "epilacao": "beleza",
    "spa": "beleza",
    "perfumaria": "beleza",
    "perfume": "beleza",
    "cosmetico": "beleza",
    "maquiagem": "beleza",
    "sephora": "beleza",
    "boticario": "beleza",
    "natura": "beleza",
    "loreal": "beleza",
    "avon": "beleza",
    "quem disse berenice": "beleza",
    "granado": "beleza",
    "bioage": "beleza",
    "contém 1g": "beleza",
    "studio": "beleza",

    # ENTRETENIMENTO
    "netflix": "entretenimento",
    "spotify": "entretenimento",
    "amazon prime": "entretenimento",
    "prime video": "entretenimento",
    "disney": "entretenimento",
    "hbo": "entretenimento",
    "cinema": "entretenimento",
    "ingresso": "entretenimento",
    "teatro": "entretenimento",
    "youtube": "entretenimento",
    "twitch": "entretenimento",
    "deezer": "entretenimento",
    "apple tv": "entretenimento",
    "paramount": "entretenimento",
    "globoplay": "entretenimento",
    "crunchyroll": "entretenimento",
    "star+": "entretenimento",
    "mubi": "entretenimento",
    "xbox": "entretenimento",
    "playstation": "entretenimento",
    "steam": "entretenimento",
    "nintendo": "entretenimento",
    "psn": "entretenimento",
    "epic games": "entretenimento",
    "riot games": "entretenimento",
    "blizzard": "entretenimento",
    "apple music": "entretenimento",
    "tidal": "entretenimento",
    "maximus": "entretenimento",
    "telecine": "entretenimento",
    "eventim": "entretenimento",
    "sympla": "entretenimento",
    "ticket": "entretenimento",

    # LAZER
    "balada": "lazer",
    "boliche": "lazer",
    "parque": "lazer",
    "museu": "lazer",
    "exposicao": "lazer",
    "karaoke": "lazer",
    "escape room": "lazer",
    "bowling": "lazer",
    "paintball": "lazer",
    "kart": "lazer",
    "clube": "lazer",
    "piscina": "lazer",
    "aquapark": "lazer",
    "laser tag": "lazer",
    "trampoline": "lazer",
    "festa": "lazer",
    "churrasqueira": "lazer",
    "sitio": "lazer",
    "chacara": "lazer",

    # COMPRAS
    "mercado livre": "compras",
    "mercadolivre": "compras",
    "shopee": "compras",
    "aliexpress": "compras",
    "alipay": "compras",
    "magalu": "compras",
    "magazine luiza": "compras",
    "americanas": "compras",
    "amazon": "compras",
    "ebay": "compras",
    "wish": "compras",
    "shein": "compras",
    "enjoei": "compras",
    "olx": "compras",
    "loja": "compras",
    "shopping": "compras",
    "bijuteria": "compras",
    "bijoux": "compras",
    "artesanato": "compras",
    "presentes": "compras",
    "gift": "compras",
    "casas bahia": "compras",
    "ponto frio": "compras",
    "extra.com": "compras",
    "netshoes": "compras",
    "centauro": "compras",
    "decathlon": "compras",

    # EDUCAÇÃO
    "curso": "educação",
    "udemy": "educação",
    "alura": "educação",
    "coursera": "educação",
    "faculdade": "educação",
    "universidade": "educação",
    "unasp atividades": "alimentação",  # Refeitório/cantina subsidiada da UNASP
    "unasp": "educação",               # Mensalidade/matrícula da UNASP
    "usp": "educação",
    "unicamp": "educação",
    "escola": "educação",
    "colegio": "educação",
    "ensino": "educação",
    "livro": "educação",
    "livraria": "educação",
    "leitura": "educação",        # Ex: "Leitura Dpedro"
    "apostila": "educação",
    "material escolar": "educação",
    "mensalidade": "educação",
    "matricula": "educação",
    "inscricao": "educação",
    "worksho": "educação",
    "treinamento": "educação",
    "submarino": "educação",      # Vende livros
    "saraiva": "educação",
    "fnac": "educação",
    "cultura": "educação",

    # MORADIA
    "aluguel": "moradia",
    "condominio": "moradia",
    "energia": "moradia",
    "luz": "moradia",
    "agua": "moradia",
    "sabesp": "moradia",
    "enel": "moradia",
    "cemig": "moradia",
    "copel": "moradia",
    "eletropaulo": "moradia",
    "internet": "moradia",
    "vivo": "moradia",
    "claro": "moradia",
    "tim": "moradia",
    "oi ": "moradia",
    "net ": "moradia",
    "gás": "moradia",
    "gas": "moradia",
    "comgas": "moradia",
    "iptu": "moradia",
    "ipva": "moradia",
    "seguro residencial": "moradia",
    "reforma": "moradia",
    "material construcao": "moradia",
    "leroy merlin": "moradia",
    "telha norte": "moradia",
    "c&c": "moradia",

    # FINANCEIRO
    "banco": "financeiro",
    "nubank": "financeiro",
    "itau": "financeiro",
    "bradesco": "financeiro",
    "santander": "financeiro",
    "caixa": "financeiro",
    "bb ": "financeiro",
    "banco do brasil": "financeiro",
    "inter": "financeiro",
    "c6": "financeiro",
    "next": "financeiro",
    "pagbank": "financeiro",
    "mercado pago": "financeiro",
    "picpay": "financeiro",
    "taxa": "financeiro",
    "juros": "financeiro",
    "tarifa": "financeiro",
    "anuidade": "financeiro",
    "seguro": "financeiro",
    "previdencia": "financeiro",
    "investimento": "financeiro",
    "tesouro": "financeiro",
    "corretora": "financeiro",
    "multa": "financeiro",
    "debito automatico": "financeiro",

    # VIAGEM
    "hotel": "viagem",
    "passagem": "viagem",
    "airbnb": "viagem",
    "booking": "viagem",
    "decolar": "viagem",
    "latam": "viagem",
    "gol ": "viagem",
    "azul ": "viagem",
    "avianca": "viagem",
    "hospedagem": "viagem",
    "pousada": "viagem",
    "resort": "viagem",
    "hostel": "viagem",
    "rodoviaria": "viagem",
    "aeroporto": "viagem",
    "mala": "viagem",
    "turismo": "viagem",
    "excursao": "viagem",
    "viagem": "viagem",
    "trivago": "viagem",
    "expedia": "viagem",
    "submarino viagens": "viagem",

    # PET
    "petshop": "pet",
    "pet shop": "pet",
    "racao": "pet",
    "veterinario": "pet",
    "veterinaria": "pet",
    "vet ": "pet",
    "cobasi": "pet",
    "petz": "pet",
    "agropecuaria": "pet",
    "banho e tosa": "pet",
    "canil": "pet",
    "aquario": "pet",
    "passaro": "pet",

    # VESTUÁRIO
    "roupa": "vestuário",
    "zara": "vestuário",
    "renner": "vestuário",
    "riachuelo": "vestuário",
    "c&a": "vestuário",
    "hering": "vestuário",
    "nike": "vestuário",
    "adidas": "vestuário",
    "puma": "vestuário",
    "fila": "vestuário",
    "calcado": "vestuário",
    "calcados": "vestuário",
    "sapataria": "vestuário",
    "sapato": "vestuário",
    "sandalia": "vestuário",
    "tenis": "vestuário",
    "havaianas": "vestuário",
    "moda": "vestuário",
    "confeccao": "vestuário",
    "outlet": "vestuário",
    "authentic feet": "vestuário",  # Recorrente no extrato
    "feet": "vestuário",
    "farm": "vestuário",
    "reserva": "vestuário",
    "aramis": "vestuário",
    "forum": "vestuário",
    "le lis blanc": "vestuário",
    "shoulder": "vestuário",

    # TECNOLOGIA
    "apple": "tecnologia",
    "google": "tecnologia",
    "microsoft": "tecnologia",
    "software": "tecnologia",
    "hardware": "tecnologia",
    "notebook": "tecnologia",
    "celular": "tecnologia",
    "smartphone": "tecnologia",
    "kabum": "tecnologia",
    "eletronico": "tecnologia",
    "eletronica": "tecnologia",
    "samsung": "tecnologia",
    "lenovo": "tecnologia",
    "dell": "tecnologia",
    "hp ": "tecnologia",
    "positivo": "tecnologia",
    "iphone": "tecnologia",
    "ipad": "tecnologia",
    "monitor": "tecnologia",
    "teclado": "tecnologia",
    "mouse": "tecnologia",
    "headset": "tecnologia",
    "fone": "tecnologia",
    "carregador": "tecnologia",
    "cabo usb": "tecnologia",
    "hd externo": "tecnologia",
    "pendrive": "tecnologia",
    "impressora": "tecnologia",
    "j filhos eletronicos": "tecnologia",  # Loja recorrente no extrato

    # SERVIÇOS
    "servico": "serviços",
    "manutencao": "serviços",
    "conserto": "serviços",
    "eletricista": "serviços",
    "encanador": "serviços",
    "limpeza": "serviços",
    "diarista": "serviços",
    "faxina": "serviços",
    "lavanderia": "serviços",
    "assistencia": "serviços",
    "tecnico": "serviços",
    "pintura": "serviços",
    "marceneiro": "serviços",
    "dedetizacao": "serviços",
    "mudanca": "serviços",
    "frete": "serviços",
    "entrega": "serviços",
    "notario": "serviços",
    "cartorio": "serviços",
    "seguranca": "serviços",
    "monitoramento": "serviços",
}


def normalizar(texto: str) -> str:
    return unicodedata.normalize("NFKD", texto).encode("ASCII", "ignore").decode("ASCII").lower()


def categorizar(descricao: str) -> str:
    descricao = normalizar(descricao)

    # Ordena pelas chaves maiores primeiro (mais específicas)
    for chave in sorted(MAPEAMENTO.keys(), key=len, reverse=True):
        if chave in descricao:
            return MAPEAMENTO[chave]

    return "Outros"
