"""create tables

Revision ID: 38252be0a60a
Revises: 
Create Date: 2026-03-17 22:33:40.281163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38252be0a60a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('gastos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gastos_usuario_categoria', 'gastos', ['usuario_id', 'categoria'], unique=False)
    op.create_index('idx_gastos_usuario_data', 'gastos', ['usuario_id', 'data_hora'], unique=False)
    op.create_index(op.f('ix_gastos_categoria'), 'gastos', ['categoria'], unique=False)
    op.create_index(op.f('ix_gastos_data_hora'), 'gastos', ['data_hora'], unique=False)
    op.create_index(op.f('ix_gastos_id'), 'gastos', ['id'], unique=False)
    op.create_index(op.f('ix_gastos_usuario_id'), 'gastos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gastos_usuario_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_data_hora'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_categoria'), table_name='gastos')
    op.drop_index('idx_gastos_usuario_data', table_name='gastos')
    op.drop_index('idx_gastos_usuario_categoria', table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
