"""add tipo to gastos

Revision ID: 2549d157e4c7
Revises: 38252be0a60a
Create Date: 2026-03-27 01:30:18.290716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2549d157e4c7'
down_revision: Union[str, Sequence[str], None] = '38252be0a60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gastos', sa.Column('tipo', sa.String(), nullable=True))
    op.create_index(op.f('ix_gastos_tipo'), 'gastos', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gastos_tipo'), table_name='gastos')
    op.drop_column('gastos', 'tipo')
    # ### end Alembic commands ###
