"""create tables

Revision ID: 4fdb32624df4
Revises: 
Create Date: 2026-03-15 23:51:59.737471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdb32624df4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('email', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('senha', sa.String(), nullable=True))
    op.drop_constraint(op.f('usuarios_usuario_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.drop_column('usuarios', 'usuario')
    op.drop_column('usuarios', 'senha_hash')
    op.drop_column('usuarios', 'ativo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('senha_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuarios', sa.Column('usuario', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_usuario_key'), 'usuarios', ['usuario'], postgresql_nulls_not_distinct=False)
    op.drop_column('usuarios', 'senha')
    op.drop_column('usuarios', 'email')
    # ### end Alembic commands ###
