"""add indexes to gastos

Revision ID: a635155d84a3
Revises: 4fdb32624df4
Create Date: 2026-03-15 23:56:33.303902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a635155d84a3'
down_revision: Union[str, Sequence[str], None] = '4fdb32624df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_gastos_usuario_categoria', 'gastos', ['usuario_id', 'categoria'], unique=False)
    op.create_index('idx_gastos_usuario_data', 'gastos', ['usuario_id', 'data_hora'], unique=False)
    op.create_index(op.f('ix_gastos_categoria'), 'gastos', ['categoria'], unique=False)
    op.create_index(op.f('ix_gastos_data_hora'), 'gastos', ['data_hora'], unique=False)
    op.create_index(op.f('ix_gastos_usuario_id'), 'gastos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gastos_usuario_id'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_data_hora'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_categoria'), table_name='gastos')
    op.drop_index('idx_gastos_usuario_data', table_name='gastos')
    op.drop_index('idx_gastos_usuario_categoria', table_name='gastos')
    # ### end Alembic commands ###
